### ISSUE TITLE
Modularised

### ISSUE THREAD

**Issue by lionfish0** [mrbaozi/triangulation#2]
Hi,
I needed a module to do earclipping. I hope you don't mind but I copied your code and reorganised it into a module to make it easy to use. Sorry about that! Maybe I could give you the ownership of the repo?

Here's a demo using the module: https://github.com/lionfish0/earclip/blob/master/jupyter/Demo.ipynb

Thanks for working out the code!

**Comment by yaugenst** [comment]
Sure, do whatever you like with it. I never expected anyone to actually use this so I didn't add a license. Fixed in be56e65840a2e4e06f49844f4dcfd73dfa957c27.

I just looked over the code (it's been a while) and spotted some issues. Mainly, InTriangle() should properly handle division by zero instead of manipulating the denominator, which causes rounding errors. Just a heads up if you intend to use the resulting triangles.
